name: af_screen
description: AF Detection & Stroke Risk Companion App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # BLE
  flutter_blue_plus: ^1.31.0

  # Local storage (no build_runner needed â€” adapters written manually)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Charts
  fl_chart: ^0.68.0

  # State management
  provider: ^6.1.2

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
